version: '3.9'

services:

  redis:
    image: redis:7.2.4-alpine
    restart: always
    hostname: redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_USERNAME=default
      - REDIS_PASSWORD=pass
      - REDIS_PORT=6379
      - REDIS_DATABASES=0

  mongo:
    image: mongo:7.0.6
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    # Persistence storage
    # volumes:
    #   - "./db/data:/db/data"

  mongo-express:
    image: mongo-express:1.0.2-20-alpine3.19
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    depends_on:
      - mongo
